services:
  postgres:
    image: postgres:latest
    container_name: "db-postgresql"
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - progresDB:/data/postgres
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env

  pgAdmin:
    image: dpage/pgadmin4
    container_name: "pgAdmin"
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - ./.env
    ports:
      - 5050:80

  backend:
    hostname: "backend"
    restart: on-failure:[3]
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      RUST_LOG: "info"
    depends_on:
      - postgres


volumes:
  progresDB:
