services:
  postgres:
    image: postgres:latest
    container_name: "db-postgresql"
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - progresDB:/data/postgres
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env

  backend:
    hostname: "backend"
    restart: no
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      RUST_LOG: "info"
    env_file:
      - ./.env
    depends_on:
      - postgres


volumes:
  progresDB:
