version: '3.8'

networks:
  todonet:

volumes:
  progresDB:

services:
  backend:
    hostname: "backend"
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - todonet
    ports:
      - 3000:3000    
    environment:
      RUST_LOG: "info"
  
  postgres:
    image: postgres:latest
    container_name: "db-postgresql"
    restart: unless-stopped
    networks:
      - todonet
    ports:
      - 6500:5432
    volumes:
      - progresDB:/data/postgres
    env_file:
      - ./.env

