version: '3.8'

services:
  backend:
    hostname: "backend"
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000    
    environment:
      RUST_LOG: "info"
