[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
graph-rs-sdk = "1.1.3"
hyper = "1.1.0"
poem = "2.0"
poem-openapi = { version = "4.0", features = ["swagger-ui"] }
serde = "1.0.195"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
